"""Merge by import strategy: imports file generation, verification, undo and trunk guard.

The overlay's created resources are handed to the trunk through generated
``import {}`` blocks committed with the branch (DESIGN 6 `merge`, DESIGN 8).
The base state is never written here (invariant 3.2).
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import TYPE_CHECKING, Any

from tofu_overlay import config
from tofu_overlay import plan as planmod
from tofu_overlay.identity import TypeKnowledge
from tofu_overlay.models import (
    BackendConfig,
    Claim,
    ClaimKind,
    Overlay,
    OverlayError,
    PolicyError,
    Status,
    ToolError,
    VerifyResult,
    Violation,
    new_run_id,
    utcnow_iso,
)
from tofu_overlay.registry import Registry

if TYPE_CHECKING:
    from tofu_overlay.overlay import OverlayService

IMPORTS_FILENAME = "zz_overlay_{name}.imports.tf"

_BLOCK_RE = re.compile(r"import\s*\{(?P<body>.*?)\n\s*\}", re.DOTALL)
_TO_RE = re.compile(r"^\s*to\s*=\s*(?P<to>.+?)\s*$", re.MULTILINE)
_ID_RE = re.compile(r'^\s*id\s*=\s*"(?P<id>(?:[^"\\]|\\.)*)"\s*$', re.MULTILINE)


def _hcl_string(value: str) -> str:
    """Quote a value as an HCL string literal."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _unquote(value: str) -> str:
    return value.replace('\\"', '"').replace("\\\\", "\\")


def _identity_comment(identity: dict[str, Any]) -> str:
    parts = [f"{k}={identity[k]}" for k in sorted(identity)]
    return "# identity: " + (", ".join(parts) if parts else "(unknown)")


def render_imports(
    ov: Overlay, *, base: BackendConfig, base_etag: str, commit: str, generated_at: str
) -> str:
    """Render the imports file: header, then one `import {}` block per create claim, sorted."""
    lines = [
        "# Generated by tofu-overlay - do not edit by hand.",
        f"# overlay: {ov.name} (branch {ov.branch})",
        f"# base: s3://{base.bucket}/{base.state_path()} (etag {base_etag})",
        f"# commit: {commit}",
        f"# generated_at: {generated_at}",
        "# Delete this file once the trunk applied the imports (`tofu-overlay finalize`).",
        "",
    ]
    for address, claim in sorted(ov.create_claims().items()):
        if not claim.import_id:
            continue
        lines += [
            _identity_comment(claim.identity),
            "import {",
            f"  to = {address}",
            f"  id = {_hcl_string(claim.import_id)}",
            "}",
            "",
        ]
    return "\n".join(lines)


def write_imports(env_dir: Path, name: str, content: str) -> Path:
    """Write the imports file in the env dir; refuse symlinked dir or target."""
    env_dir = Path(env_dir)
    if env_dir.is_symlink():
        raise ToolError(f"{env_dir} is a symlink, refusing to write the imports file")
    target = env_dir / IMPORTS_FILENAME.format(name=name)
    if target.is_symlink():
        raise ToolError(f"{target} is a symlink, refusing to overwrite it")
    target.write_text(content)
    return target


def read_imports_addresses(path: Path) -> dict[str, str]:
    """Parse `import {}` blocks back into {address: id}."""
    text = Path(path).read_text()
    out: dict[str, str] = {}
    for block in _BLOCK_RE.finditer(text):
        body = block.group("body")
        to = _TO_RE.search(body)
        id_ = _ID_RE.search(body)
        if to and id_:
            out[to.group("to").strip()] = _unquote(id_.group("id"))
    return out


class MergeService:
    """Import-strategy merge on top of an OverlayService."""

    def __init__(self, svc: OverlayService) -> None:
        self.svc = svc
        self.allow_import_updates = False

    # ------------------------------------------------------------------ helpers

    @property
    def imports_path(self) -> Path:
        """Path of this overlay's imports file in the env dir."""
        return self.svc.cwd / IMPORTS_FILENAME.format(name=self.svc.name)

    def _check_commit(self, ov: Overlay, *, allow_unapplied: bool) -> None:
        head = config.head_commit(self.svc.cwd)
        problems = []
        if ov.applied_commit != head:
            problems.append(f"HEAD {head[:12]} != applied commit {(ov.applied_commit or '?')[:12]}")
        if config.is_tree_dirty(self.svc.cwd):
            problems.append("working tree is dirty")
        if not problems:
            return
        if allow_unapplied:
            self.svc.console.warn("; ".join(problems) + " (--allow-unapplied)")
            return
        raise PolicyError("; ".join(problems) + "; apply and commit first (or --allow-unapplied)")

    def _refreshed_claims(self, ov: Overlay, overlay_doc: dict) -> dict[str, Claim]:
        missing = self.svc._missing_create_claims(ov, overlay_doc)
        if missing:
            raise PolicyError(
                "create claims without instance in the overlay state (run `apply`): "
                + ", ".join(missing)
            )
        return self.svc._claims_from_state(ov.claims, overlay_doc)

    def _non_importable(
        self, claims: dict[str, Claim], accept_recreate: set[str]
    ) -> tuple[list[str], list[str]]:
        """(refused, warnings) over create claims: non-importable / replace-prone / no import id."""
        knowledge = self.svc.knowledge
        refused, warnings = [], []
        for address, claim in sorted(claims.items()):
            if claim.kind != ClaimKind.CREATE:
                continue
            reason = None
            if not knowledge.is_importable(claim.type):
                reason = "non-importable type"
            elif knowledge.is_replace_prone(claim.type):
                reason = "replace-prone type"
            elif not claim.import_id:
                reason = "no import id could be computed"
            if reason is None:
                if not knowledge.known(claim.type):
                    warnings.append(f"{address}: no import format for {claim.type}, using {{id}}")
                continue
            if address in accept_recreate:
                warnings.append(f"{address}: {reason}, accepted for recreation by the trunk")
            else:
                refused.append(f"{address} ({claim.type}: {reason})")
        return refused, warnings

    # ------------------------------------------------------------------ merge

    def merge(
        self,
        *,
        allow_import_updates: bool,
        accept_recreate: list[str],
        allow_unapplied: bool,
        yes: bool,
    ) -> Path:
        """Write the imports file, verify against the base, flip the overlay to `merging`."""
        svc = self.svc
        self.allow_import_updates = allow_import_updates
        _doc, ov = svc._load()
        status = svc._effective_status(ov)
        if status == Status.MERGING:
            raise PolicyError(f"overlay '{ov.name}' is already merging; use `merge --undo`")
        if status == Status.DIRTY:
            raise PolicyError(f"overlay '{ov.name}' is dirty (last apply failed); fix it first")
        svc._gate(ov, {Status.ACTIVE}, "merge")
        svc.refuse_symlinked_env()
        overlay_doc = svc._validate_overlay(ov)
        stale, base_etag = svc._freshness(ov)
        if stale:
            svc.console.warn("overlay is stale: the verify plan runs against a moved base")
        self._check_commit(ov, allow_unapplied=allow_unapplied)
        claims = self._refreshed_claims(ov, overlay_doc)
        accepted = set(accept_recreate)
        refused, warnings = self._non_importable(claims, accepted)
        for w in warnings:
            svc.console.warn(w)
        if refused:
            raise PolicyError(
                "non-importable create claims (use --accept-recreate ADDR,...): "
                + ", ".join(refused)
            )
        rendered = ov.model_copy(
            update={"claims": {a: c for a, c in claims.items() if a not in accepted}}
        )
        content = render_imports(
            rendered,
            base=svc.backend,
            base_etag=base_etag,
            commit=config.head_commit(svc.cwd),
            generated_at=utcnow_iso(),
        )
        path = write_imports(svc.cwd, ov.name, content)
        svc.console.info(f"wrote {path.name} ({len(rendered.create_claims())} import block(s))")
        try:
            result = self.verify(accepted=accepted)
            for w in result.warnings:
                svc.console.warn(w)
            if result.drift:
                svc.console.info(
                    f"trunk drift tolerated: {len(result.drift)} address(es) "
                    f"({', '.join(result.drift)})"
                )
            if not result.ok:
                raise PolicyError("merge verification failed: " + "; ".join(result.errors))
            if not svc.console.confirm(f"Freeze overlay '{ov.name}' as merging?", yes=yes):
                raise ToolError("merge aborted")
            # Precondition: nothing (e.g. a CI apply) touched the entry since it was loaded.
            svc.registry.set_status(
                ov.name,
                Status.MERGING,
                expect_status={Status.ACTIVE},
                expect_entry=ov,
                claims=claims,
            )
        except Exception:
            path.unlink(missing_ok=True)
            raise
        svc.console.success(f"overlay '{ov.name}' is merging; commit {path.name} with the branch")
        return path

    def undo(self, *, yes: bool) -> None:
        """Delete the imports file and return the overlay to `active`."""
        svc = self.svc
        _doc, ov = svc._load()
        if ov.status != Status.MERGING:
            raise PolicyError(f"overlay '{ov.name}' is {ov.status}, nothing to undo")
        if not svc.console.confirm(f"Undo merge of '{ov.name}'?", yes=yes):
            raise ToolError("undo aborted")
        if self.imports_path.exists():
            self.imports_path.unlink()
            svc.console.info(f"removed {self.imports_path.name}")
        svc.registry.set_status(ov.name, Status.ACTIVE, expect_status={Status.MERGING})
        svc.console.success(f"overlay '{ov.name}' is active again")

    def _trunk_drift(self) -> dict[str, list[str]] | None:
        """The trunk baseline (cached with `plan`'s), or None when it cannot be computed.

        A base ``update`` the trunk config produces too is not the branch's
        doing: it must not block the merge (DESIGN 8). Without a baseline the
        rule stays the stricter one, so the operator is told why.
        """
        try:
            baseline = self.svc.trunk_baseline()
        except OverlayError as exc:
            self.svc.console.warn(
                f"trunk baseline unavailable ({exc}); every update outside the overlay's "
                "claims blocks the merge"
            )
            return None
        if baseline is None:
            self.svc.console.warn(
                "trunk baseline unavailable; every update outside the overlay's claims "
                "blocks the merge"
            )
        return baseline

    def verify(self, *, accepted: set[str] | None = None) -> VerifyResult:
        """Plan the branch config against the base state (base data dir), check DESIGN 8.

        ``accepted`` are the create claims left out of the imports file
        (``--accept-recreate``); by default they are derived from the file.
        Updates the trunk baseline also carries are tolerated as trunk drift,
        exactly as `plan` classifies them.
        """
        svc = self.svc
        _doc, ov = svc._load()
        if accepted is None:
            accepted = svc._accepted_recreate(ov)
        runner = svc._base_runner()
        planfile = svc.base_data_dir / f"tfplan.verify.{new_run_id()}"
        try:
            runner.plan(planfile)
            changes, _drift, summary = planmod.parse_plan(runner.show_json(planfile))
        finally:
            planfile.unlink(missing_ok=True)
        svc.console.info("verify plan: " + planmod.render_summary(summary))
        return planmod.verify_import_plan(
            changes,
            me=ov,
            knowledge=svc.knowledge,
            allow_import_updates=self.allow_import_updates,
            accepted_recreate=accepted,
            trunk_drift=self._trunk_drift(),
        )


def guard(plan_json_path: Path, *, registry: Registry, knowledge: TypeKnowledge) -> list[Violation]:
    """Trunk pipeline gate: violations of a trunk plan against the registry (read-only)."""
    try:
        show_json = json.loads(Path(plan_json_path).read_text())
    except (OSError, json.JSONDecodeError) as exc:
        raise ToolError(f"cannot read plan JSON {plan_json_path}: {exc}") from exc
    changes, _drift, _summary = planmod.parse_plan(show_json)
    doc, _etag = registry.load()
    return planmod.guard_trunk_plan(changes, doc=doc, knowledge=knowledge, overlay_states=None)


__all__ = [
    "IMPORTS_FILENAME",
    "MergeService",
    "guard",
    "read_imports_addresses",
    "render_imports",
    "write_imports",
]
